### ISSUE TITLE
make it easy to set the main verticle in code

### ISSUE THREAD

**Issue by bitkid** [eclipse-vertx/vertx-launcher#10]
i dont know how exactly .. either add getMainVerticle to VertxApplicationHooks? or some other way?

**Comment by tsegismont** [comment]
Not sure what you mean, can you please explain what you'd like to achieve?

**Comment by bitkid** [comment]
the Launcher class in 4.x had a method getMainVerticle(): String which i could overwrite and return the name of my main verticle. when i packaged everything together in my fat.jar i could just launch it with java -jar fat.jar. now i either have to have that name in a manifest file oder pass it in the command line. i couldn't find an easy  way to set it in my code.

**Comment by tsegismont** [comment]
You can also override `io.vertx.launcher.application.VertxApplicationHooks#verticleSupplier`
